

INSERT INTO tenants_schema.tenant ( 
  tenant_mission,  
  tenant_phone,  
  tenant_address_ar,  
  tenant_logo,  
  tenant_logo_vertical,  
  tenant_logo_dark_vertical,  
  tenant_name,  
  tenant_description,  
  tenant_values,  
  tenant_vision,  
  tenant_links,  
  tenant_name_ar,  
  tenant_address,  
  tenant_description_ar,  
  tenant_email,  
  tenant_logo_dark
) VALUES
  (
          'To revolutionize technology', 
          '+2 035857764 ', 
          'Madinet Elahlam, 724 El-Horeya Rd, لوران، Qesm AR Ramel، Alexandria Governorate 5451112', 
          'tenats/abchotels.svg', 
          'tenats/abchotels.svg', 
          'tenats/abchotels_light.svg', 
          'ABC Hotels', 
          'The ABC Hotels company has the capability to assist business owners in securing investment opportunities and planning for them in terms of location, construction, implementation, and operation of hotels, resorts, service apartments, and restaurants  The company’s expertise and resources can support business owners throughout the entire life cycle of a hospitality project - from site selection and feasibility analysis to design, construction, and operational management. ABC Hotels’ comprehensive approach allows investors to leverage the company’s proven track record and industry knowledge to bring their hospitality ventures to fruition.  Overall, the ABC Hotels company is positioned to be a valuable strategic partner for business owners seeking to capitalize on opportunities in the hospitality sector. Its ability to provide end to-end support can streamline the investment process and increase the likelihood of a project’s long-term viability and profitability.', 
          'Innovation|Integrity|Excellence', 
          'To be the global leader in tech', 
          '{   "facebook": "https://www.facebook.com/profile.php?id=61565334736199",   "instagram": "https://www.instagram.com/rhactushousesanstefano",   "linkedin": "https://www.linkedin.com/company/rhactushousesanstefano/" }', 
          ' ABC Hotels ', 
          'Madinet Elahlam, 724 El-Horeya Rd, لوران، Qesm AR Ramel، Alexandria Governorate 5451112', 
          'شركة اي بي سي هوتلز لديها القدرة على مساعدة أصحاب الأعمال في تأمين فرص الاستثمار والتخطيط لها من حيث الموقع والبناء والتنفيذ والتشغيل للفنادق والمنتجعات والشقق الفندقية والمطاعم. يمكن أن تدعم خبرات الشركة ومواردها أصحاب الأعمال طوال دورة حياة مشروع الضيافة بأكملها - من اختيار الموقع وتحليل الجدوى إلى التصميم والبناء والإدارة التشغيلية. يتيح النهج الشامل لشركة اي بي سي هوتلز للمستثمرين الاستفادة من سجل الشركة الحافل بالانجازات ومعرفتها الصناعية لتحقيق مشاريعهم في مجال الضيافة. بشكل عام، فإن شركة اي بي سي هوتلز في وضع يسمح لها بأن تكون شريكًا استراتيجيًا قيّمًا لأصحاب الأعمال الذين يسعون إلى الاستفادة من الفرص في قطاع الضيافة. ويمكن لقدرتها على تقديم الدعم الشامل تبسيط عملية الاستثمار وزيادة احتمالية الجدوى والربحية طويلة الأجل للمشروع.', 
          'info@abchotels-eg.com', 
          'tenats/abchotels_light.svg'
  ), 
  (
          'To lead sustainable transformation in sand and soil stabilization across the Gulf', 
          '+966 596 888 111', 
          'المملكة العربية السعودية', 
          'tenants/gulfelite.svg', 
          'tenants/gulfelite_vertical.svg', 
          'tenants/gulfelite_dark_vertical.svg', 
          'Gulf Elite Chemicals', 
          'Gulf Elite Chemicals is a Saudi-based environmental technology company specializing in chemical solutions for sand and soil stabilization. With proprietary, eco-friendly formulations and a proven track record in extreme desert environments, GEC provides both bulk product sales and turnkey stabilization services to clients such as Aramco, the Ministry of Transportation, and Saudi Railways.', 
          'Eco-Consciousness|Local Expertise|Technical Excellence', 
          'To become the MENA region’s foremost provider of eco-friendly stabilization technologies', 
          '{   "website": "https://www.gulfelite.sa",   "linkedin": "",   "instagram": "" }', 
          'جلف إيليت كيميكالز', 
          'Kingdom of Saudi Arabia', 
          'تُعد شركة جلف إيليت كيميكالز شركة سعودية متخصصة في تقنيات الحفاظ على البيئة من خلال حلول كيميائية لتثبيت التربة والرمال. وتقدم الشركة منتجات صديقة للبيئة ذات تركيبة فريدة، إلى جانب خدمات تنفيذية شاملة في أصعب البيئات الصحراوية، وتخدم عملاء مثل أرامكو ووزارة النقل وسكك حديد السعودية.', 
          'info@GulfElite.sa', 
          'tenants/gulfelite_dark.svg'
  );
	


INSERT INTO tenants_schema.page ( 
  page_description_ar,  
  page_breadcrumb,  
  page_cover_image,  
  page_key_words,  
  page_meta_description,  
  page_name,  
  page_description,  
  tenant_id,  
  page_route,  
  page_cover_video,  
  page_icon,  
  page_name_ar
) VALUES
  (
          'الصفحة الرئيسية الفعلية', 
          'Home', 
          'home_cover.png', 
          'landing,homepage,company', 
          'Welcome to our homepage', 
          'Home', 
          'The main landing page', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'ABC Hotels'), 
          '/home', 
          'home_video.mp4', 
          'home', 
          'الصفحة الرئيسية'
  ), 
  (
          'عن شركتنا', 
          'About us', 
          'about_cover.png', 
          'about,company,info', 
          'Learn more about us', 
          'About Us', 
          'About our company', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'ABC Hotels'), 
          '/about', 
          'about_video.mp4', 
          'about', 
          'من نحن'
  ), 
  (
          'مشاريعنا', 
          'Projects', 
          'projects_cover.png', 
          'projects,portfolio,work', 
          'Discover our work', 
          'Projects', 
          'Our projects', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'ABC Hotels'), 
          '/projects', 
          'projects_video.mp4', 
          'projects', 
          'المشاريع'
  ), 
  (
          'الخدمات التي نقدمها', 
          'Services', 
          'services_cover.png', 
          'services,offerings,solutions', 
          'Explore our services', 
          'Services', 
          'Services we offer', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'ABC Hotels'), 
          '/services', 
          'services_video.mp4', 
          'services', 
          'الخدمات'
  ), 
  (
          'الاستوديو', 
          'Gallery', 
          'gallery_cover.png', 
          'gallery,abc hotels gallery,abc hotels', 
          'view abc hotels gallery ', 
          'Gallery', 
          'The company gallery', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'ABC Hotels'), 
          '/gallery', 
          'gallery_video.mp4', 
          'gallery', 
          'الاستوديو'
  ), 
  (
          'صفحة اتصل بنا', 
          'Contact', 
          'contact_cover.png', 
          'contact,email,phone,location', 
          'Get in touch with us', 
          'Contact', 
          'Contact us page', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'ABC Hotels'), 
          '/contact', 
          'contact_video.mp4', 
          'contact', 
          'اتصل بنا'
  );
	


INSERT INTO tenants_schema.section ( 
  section_button_page_id,  
  section_name,  
  section_name_ar,  
  tenant_id,  
  section_button_label,  
  section_header,  
  section_header_ar,  
  section_description,  
  section_description_ar,  
  section_background,  
  section_images
) VALUES
  (
          (SELECT page_id FROM tenants_schema.page WHERE page_name = 'about us'), 
          'home banner', 
          'الصورة الافتاحية', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'ABC Hotels'), 
          'Explore Our Story', 
          ' ABC Hotels <br />  <small>Attention to Basics & Culture</small> ', 
          'إقامة بلمسة فريدة  ', 
          'Where seamless management meets exceptional hospitality', 
          'من خلال إدارة متميزة وخدمة عالية الرفاهية 
', 
          '/abchotels/banner.webp', 
          NULL
  ), 
  (
          NULL, 
          'home about', 
          'عن الشركة', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'ABC Hotels'), 
          NULL, 
          NULL, 
          NULL, 
          '<p><strong>ABC Hotels welcomes you to a world where comfort meets precision!</strong></p><p></p><p>With a strong foundation in hospitality expertise and a genuine commitment to excellence, we craft experiences that delight guests and support property owners. Every space, service, and system is designed with care—ensuring each stay is effortlessly smooth and truly memorable.</p>', 
          'Step into a world of exceptional hospitality with ABC Hotels. With a perfect mix of expertise and commitment, ABC focuses on enhancing guest experiences while optimizing operations for property owners. From top-tier amenities to prime locations, every detail is carefully managed to ensure each stay is not just memorable, but a treasured experience for our guests', 
          '/abchotels/hotels-management.webp', 
          NULL
  ), 
  (
          NULL, 
          'home services', 
          'الخدمات', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'ABC Hotels'), 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL
  ), 
  (
          NULL, 
          'hotels', 
          'اهدافنا', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'ABC Hotels'), 
          NULL, 
          '<strong>Driven by Excellence &amp; Built on Expertise</strong>', 
          NULL, 
          '<p>At <strong>ABC Hotels</strong>, we proudly manage a diverse portfolio of properties on behalf of our esteemed clients, each offering a unique blend of luxury, comfort, and tailored service. From serene seaside retreats to vibrant city escapes and picturesque destinations, each location is carefully curated to provide guests with exceptional experiences. Our properties embody our commitment to excellence, featuring world-class amenities, outstanding hospitality, and meticulous attention to detail, ensuring every stay is memorable.</p>', 
          ' نفخر في فنادق ABC بإدارة مجموعة مميزة من الفنادق، حيث يقدم كل منها مزيجًا فريدًا من الفخامة والراحة والخدمة الشخصية. سواء كان ذلك في إجازة هادئة على الشاطئ، أو ملاذًا حضريًا مفعمًا بالحيوية، أو إقامة ساحرة في أحد المدن المميزة، تستطيع مواقعنا توفير تجارب لا تُنسى.   كل مشروع يعكس التزامنا بالتميز، مما يضمن للضيوف مرافق من فئة عالمية، ضيافة استثنائية، وسلاسة أدق التفاصيل خلال إقامتهم. استكشف واختبر الفرق مع فنادق ABC.', 
          NULL, 
          NULL
  ), 
  (
          NULL, 
          'about intro', 
          'عن الشركة', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'ABC Hotels'), 
          NULL, 
          NULL, 
          NULL, 
          '<div class="full text-center md:w-7"><p><strong>ABC Hotels</strong> serves as a strategic partner for business owners seeking to invest in the hospitality sector, offering end-to-end support across hotel, resort, serviced apartment, and restaurant projects. With expertise spanning site selection, feasibility analysis, design, construction, and operational management, <strong>ABC Hotels</strong> provides the insight and resources needed to bring hospitality ventures to life.</p><p>By leveraging our industry experience and integrated approach, investors can streamline development, reduce risk, and enhance long-term profitability. From concept to completion, <strong>ABC Hotels</strong> is equipped to guide you through every stage of the project lifecycle ensuring your investment is positioned for sustained success.</p></div>', 
          NULL, 
          NULL, 
          '/abchotels/rhactus-new-alamein.webp,/abchotels/rhactus-new-alamein-2.webp,/abchotels/hotels-management.webp'
  ), 
  (
          NULL, 
          'team', 
          'فريق العمل', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'ABC Hotels'), 
          NULL, 
          'Meet The Team', 
          NULL, 
          'ABC Hotels’ leadership team is comprised of seasoned hospitality experts with extensive industry experience and commitment to excellence. The team’s expertise spans senior executive positions at renowned international hospitality companies and developers. ABC Hotels’ founders have a proven track record of managing world-class hospitality projects, and a deep understanding of local and international concepts, thus introducing local cultures to the international communities.', 
          NULL, 
          NULL, 
          NULL
  ), 
  (
          NULL, 
          'services', 
          'الخدمات', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'ABC Hotels'), 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL
  ), 
  (
          NULL, 
          'projects', 
          'المشروعات', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'ABC Hotels'), 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL
  ), 
  (
          NULL, 
          'gallery', 
          'الاستوديو', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'ABC Hotels'), 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL
  ), 
  (
          NULL, 
          'contact us', 
          'اتصل بنا', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'ABC Hotels'), 
          NULL, 
          'contact us', 
          NULL, 
          'At ABC Hotels, your comfort and satisfaction are our highest priorities. If you have any questions regarding your reservation, need assistance with planning your stay, or want to learn more about our exclusive offers and services, we''re here to assist you.', 
          NULL, 
          NULL, 
          NULL
  ), 
  (
          (SELECT page_id FROM tenants_schema.page WHERE page_name = 'about us'), 
          'home banner', 
          'الصورة الافتتاحية', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'Gulf Elite Chemicals'), 
          'Learn More', 
          'Gulf Elite Chemicals <br /> <small>Eco-Innovation for Desert Environments</small>', 
          'حلول بيئية مبتكرة لبيئات الصحراء', 
          'Eco-Friendly Stabilization. Saudi Innovation. Built for Harsh Terrain.', 
          'حلول تثبيت صديقة للبيئة. ابتكار سعودي. مصممة للبيئات القاسية.', 
          '/gulfelite/banner.webp', 
          NULL
  ), 
  (
          NULL, 
          'home about', 
          'عن الشركة', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'Gulf Elite Chemicals'), 
          NULL, 
          NULL, 
          NULL, 
          'Gulf Elite Chemicals is a pioneering Saudi company delivering cutting-edge chemical solutions for sand and soil stabilization. With deep regional expertise and a mission for environmental responsibility, GEC produces and applies its proprietary SandLOCK formula to serve critical infrastructure and energy projects across the Kingdom.', 
          'تُعد جلف إيليت كيميكالز شركة سعودية رائدة في تقديم حلول كيميائية متقدمة لتثبيت الرمال والتربة. وبفضل خبرتها العميقة في المنطقة ورؤيتها البيئية، تنتج الشركة وتطبق تركيبة SandLOCK الخاصة بها لخدمة مشاريع البنية التحتية والطاقة الحيوية في المملكة.', 
          '/gulfelite/about.webp', 
          NULL
  ), 
  (
          (SELECT page_id FROM tenants_schema.page WHERE page_name = 'services'), 
          'home services', 
          'الخدمات', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'Gulf Elite Chemicals'), 
          'View Services', 
          'Our Solutions', 
          'حلولنا', 
          'Our offerings range from bulk sales of SandLOCK polymer to full-scale turnkey soil stabilization services. Engineered for performance and simplicity.', 
          'نقدم خدماتنا من بيع بالجملة لمادة SandLOCK إلى حلول متكاملة لتثبيت التربة. مصممة للأداء والبساطة.', 
          '/gulfelite/services.webp', 
          NULL
  ), 
  (
          NULL, 
          'solutions', 
          'حلولنا', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'Gulf Elite Chemicals'), 
          NULL, 
          'Tailored for Saudi Terrain', 
          'مصممة خصيصًا للبيئة السعودية', 
          'From slope protection to desert road stabilization, our customized applications are built to last in extreme weather. Each project leverages GEC’s proprietary materials and expert field execution.', 
          'من حماية المنحدرات إلى تثبيت الطرق الصحراوية، يتم تصميم تطبيقاتنا لتدوم في أقسى الظروف. تستند جميع المشاريع إلى المواد الخاصة بنا والتنفيذ الميداني الاحترافي.', 
          NULL, 
          NULL
  ), 
  (
          NULL, 
          'about intro', 
          'عن الشركة', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'Gulf Elite Chemicals'), 
          NULL, 
          NULL, 
          NULL, 
          '<p class=\"mb-3\"> Gulf Elite Chemicals is an environmentally responsible, Saudi-owned company delivering pioneering sand and soil stabilization solutions. </p> <p class=\"mb-3\"> Our signature product SandLOCK is locally manufactured using eco-friendly materials and engineered specifically for Gulf conditions. </p> <p> With experience in the most extreme desert environments, we help stabilize infrastructure, protect natural resources, and minimize environmental impact. </p>', 
          NULL, 
          NULL, 
          '/gulfelite/plant.webp,/gulfelite/application.webp,/gulfelite/shaybah.webp'
  ), 
  (
          NULL, 
          'team', 
          'فريق العمل', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'Gulf Elite Chemicals'), 
          NULL, 
          'Meet the Experts', 
          'تعرف على فريقنا', 
          'Gulf Elite Chemicals is powered by a team of chemical engineers, application specialists, and project managers with decades of experience in regional stabilization projects and polymer science.', 
          'فريقنا يضم مهندسين كيميائيين، ومختصين في التطبيقات، ومديري مشاريع يتمتعون بخبرة طويلة في مشاريع التثبيت الإقليمي وعلوم البوليمرات.', 
          NULL, 
          NULL
  ), 
  (
          NULL, 
          'services', 
          'الخدمات', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'Gulf Elite Chemicals'), 
          NULL, 
          'What We Offer', 
          'ماذا نقدم', 
          'Explore our chemical sales, turnkey application, and specialty sand stabilization services. Engineered for large-scale performance.', 
          'تعرف على خدماتنا في بيع المواد الكيميائية، والتنفيذ المتكامل، وحلول التثبيت المتخصصة. صممت لأداء عالي النطاق.', 
          NULL, 
          NULL
  ), 
  (
          NULL, 
          'projects', 
          'المشروعات', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'Gulf Elite Chemicals'), 
          NULL, 
          'Case Studies', 
          'دراسات الحالة', 
          'From Aramco’s Shaybah dunes to urban utility projects, our portfolio spans over 7 million m² of stabilized land.', 
          'من كثبان الشيبية التابعة لأرامكو إلى مشاريع البنية التحتية الحضرية، تمتد مشاريعنا لأكثر من 7 ملايين متر مربع من الأراضي المثبتة.', 
          NULL, 
          NULL
  ), 
  (
          NULL, 
          'gallery', 
          'الاستوديو', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'Gulf Elite Chemicals'), 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL
  ), 
  (
          NULL, 
          'contact us', 
          'اتصل بنا', 
          (SELECT tenant_id FROM tenants_schema.tenant WHERE tenant_name = 'Gulf Elite Chemicals'), 
          NULL, 
          'Contact Us', 
          'تواصل معنا', 
          'Whether you need bulk SandLOCK supply or complete stabilization services, our team is here to help. Let’s build a stable future together.', 
          'سواء كنت بحاجة إلى توريد كميات كبيرة من SandLOCK أو خدمات التثبيت الكاملة، فريقنا جاهز لمساعدتك. لنبنِ مستقبلًا مستقرًا معًا.', 
          NULL, 
          NULL
  );
	


INSERT INTO tenants_schema.partial_type ( 
  partial_type_name
) VALUES
  (
          'home service'
  ), 
  (
          'logo'
  ), 
  (
          'hotel'
  ), 
  (
          'team member'
  ), 
  (
          'service'
  ), 
  (
          'project'
  ), 
  (
          'gallery'
  ), 
  (
          'banner'
  );
	


INSERT INTO tenants_schema.page_section ( 
  page_id,  
  partial_type_id,  
  section_id,  
  is_featured
) VALUES
  (
          (SELECT page_id FROM tenants_schema.page WHERE page_name = 'Home'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'banner'), 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'home banner'), 
          'FALSE'
  ), 
  (
          (SELECT page_id FROM tenants_schema.page WHERE page_name = 'Home'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'home service'), 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'home about'), 
          'FALSE'
  ), 
  (
          (SELECT page_id FROM tenants_schema.page WHERE page_name = 'Home'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'home service'), 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'home services'), 
          'FALSE'
  ), 
  (
          (SELECT page_id FROM tenants_schema.page WHERE page_name = 'Home'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'hotel'), 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'hotels'), 
          'FALSE'
  ), 
  (
          (SELECT page_id FROM tenants_schema.page WHERE page_name = 'About Us'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'home service'), 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'about intro'), 
          'FALSE'
  ), 
  (
          (SELECT page_id FROM tenants_schema.page WHERE page_name = 'About Us'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'team member'), 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'team'), 
          'FALSE'
  ), 
  (
          (SELECT page_id FROM tenants_schema.page WHERE page_name = 'Services'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'service'), 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'services'), 
          'FALSE'
  ), 
  (
          (SELECT page_id FROM tenants_schema.page WHERE page_name = 'Projects'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'project'), 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'projects'), 
          'FALSE'
  ), 
  (
          (SELECT page_id FROM tenants_schema.page WHERE page_name = 'Gallery'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'gallery'), 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'gallery'), 
          'FALSE'
  ), 
  (
          (SELECT page_id FROM tenants_schema.page WHERE page_name = 'Contact'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'service'), 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'contact us'), 
          'FALSE'
  );
	


INSERT INTO tenants_schema.partial ( 
  partial_code,  
  partial_image,  
  partial_links,  
  address,  
  section_id,  
  partial_type_id,  
  partial_content,  
  partial_name,  
  partial_images,  
  partial_link,  
  partial_button_icon,  
  partial_brief,  
  partial_button_label,  
  partial_button_link
) VALUES
  (
          'h-1', 
          'abchotels/rhactus-new-alamein.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'hotels'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'hotel'), 
          NULL, 
          'Rhactus New Alamein', 
          NULL, 
          'https://rhactushotel.com/', 
          NULL, 
          'NEW ALAMEIN', 
          NULL, 
          NULL
  ), 
  (
          'h-2', 
          'abchotels/rhactus-house-san-stefano.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'hotels'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'hotel'), 
          NULL, 
          'Rhactus House San Stefano', 
          NULL, 
          'https://rhss.rhactushotel.com/', 
          NULL, 
          'ALEXANDRIA', 
          NULL, 
          NULL
  ), 
  (
          'h-3', 
          'abchotels/borg-al-arab-hotel.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'hotels'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'hotel'), 
          NULL, 
          'Rhactus Hotel Borg Al Arab', 
          NULL, 
          'https://rhactushotel.com/', 
          NULL, 
          'ALEXANDRIA', 
          NULL, 
          NULL
  ), 
  (
          'h-4', 
          'abchotels/marsa-wazar-hotel.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'hotels'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'hotel'), 
          NULL, 
          'Wazar Bay Resort', 
          NULL, 
          NULL, 
          NULL, 
          'MARSA WAZAR', 
          NULL, 
          NULL
  ), 
  (
          'hs-1', 
          'abchotels/hotels-management.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'home services'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'home service'), 
          NULL, 
          'Hotel Management & Operations', 
          NULL, 
          NULL, 
          NULL, 
          '<strong>ABC Hotels</strong> delivers full-service management across its properties, ensuring seamless operations and exceptional guest satisfaction. From tailored services and premium amenities to customized event and dining solutions, we maintain the highest standards of quality and care at every touchpoint.', 
          NULL, 
          NULL
  ), 
  (
          'hs-2', 
          'abchotels/yalabina-reservation-platform.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'home services'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'home service'), 
          NULL, 
          'Yalabina Reservation Platform ', 
          NULL, 
          NULL, 
          NULL, 
          '<p><strong>ABC Hotels</strong> proudly introduces <strong>Yalabina </strong>a smart, user-friendly reservation platform that makes booking seamless across all our properties. With real-time availability, secure payments, and personalized options, <strong>Yalabina </strong>simplifies travel for both business and leisure guests.</p>', 
          NULL, 
          NULL
  ), 
  (
          'hs-3', 
          'abchotels/property-management-system.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'home services'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'home service'), 
          NULL, 
          'Property Management System', 
          NULL, 
          NULL, 
          NULL, 
          '<p><strong>ABC’’s proprietary Property Management System (PMS)</strong> is built to streamline operations for hotels and residential properties. Designed for owners and operators, it centralizes reservations, front desk, housekeeping, billing, and reporting—enhancing efficiency, guest satisfaction, and profitability.</p>', 
          NULL, 
          NULL
  ), 
  (
          'hs-4', 
          'abchotels/pretzel-burger.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'home services'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'home service'), 
          NULL, 
          'Pretzel Burger', 
          NULL, 
          NULL, 
          NULL, 
          '<p><strong>Pretzel Burgers</strong>, owned by <strong>ABC Hotels</strong> in El Alamein, serves gourmet burgers with a twist crafted in soft, flavorful pretzel buns. From juicy beef to succulent shrimp, each burger is made with premium ingredients. Whether it’’s a quick bite or a casual hangout, Pretzel Burgers delivers bold flavors and great service in every visit.</p>', 
          NULL, 
          NULL
  ), 
  (
          'p-1', 
          'abchotels/rhactus-new-alamein.webp', 
          '{   "facebook": "https://www.facebook.com/rhactushotelnewalamein/",   "instagram": "https://www.instagram.com/rhactushotelnewalamein",   "linkedin": "https://www.linkedin.com/company/rhactushotelnewalamein" }', 
          'North Coast, K102 Alexandria - Marsa Matrouh Coastal Road, New Alamein City, 51718 El Alamein, Egypt', 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'projects'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'project'), 
          '<p>A refined hotel complex in the heart of New Alamein City, blending modern luxury with thoughtful hospitality. Designed for both business and leisure travelers seeking comfort, style, and convenience in a prime location.</p>', 
          'Rhactus Hotel New Alamein', 
          'abchotels/resturant.webp,abchotels/meetings.webp,abchotels/gym.webp,,abchotels/coffee-shop.webp,,abchotels/pool.webp,abchotels/room.webp', 
          NULL, 
          NULL, 
          NULL, 
          'View Website', 
          'https://rhactushotel.com/'
  ), 
  (
          'p-2', 
          'abchotels/rhactus-house-san-stefano.webp', 
          '{ "facebook" : "https://www.facebook.com/profile.php?id=61565334736199" ,    "instagram": "https://www.instagram.com/rhactushousesanstefano/", "linkedin": "https://www.linkedin.com/company/rhactushousesanstefano?fbclid=PAZXh0bgNhZW0CMTEAAaYKUBr7SX_dyOA9vFzYVlZwoFv2juCymvJ6WE9uoiJwk6lVwNWUlOS61yM_aem_RFHPj3k_Hkn66AP_ay4_jg" }', 
          '402 El-Gaish Road, 5452054 Alexandria', 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'projects'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'project'), 
          'Boutique serviced apartments in Alexandria''s prime location, combining historical charm with modern luxury and Mediterranean views.', 
          'Rhactus House  San Stefano', 
          'abchotels/rhactus-house-san-stefano.webp,abchotels/rhss-kitchen.webp,abchotels/rhss-room.webp,abchotels/rhss-view.webp', 
          NULL, 
          NULL, 
          NULL, 
          'View Website', 
          'https://rhss.rhactushotel.com/'
  ), 
  (
          'p-3', 
          'abchotels/rhactus-borg-al-arab.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'projects'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'project'), 
          '<p><strong>Rhactus Hotel Borg El Arab</strong> is a premium hotel complex set to open by the end of 2025, located in the heart of <strong>Borg El Arab</strong>. Designed for both business and leisure travelers, the property will offer modern amenities, refined accommodations, and exceptional hospitality services. With a focus on comfort, efficiency, and contemporary design, it will serve as a distinguished destination for discerning guests in one of Egypt’s emerging hubs.</p>', 
          'Rhactus Hotel Borg Al Arab', 
          'abchotels/rhactus-borg-al-arab.webp', 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL
  ), 
  (
          'p-4', 
          'abchotels/wazar-bay-resort.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'projects'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'project'), 
          '<p>Opening by the end of 2026, <strong>Wazar Bay Resort</strong> is an upcoming adults-only retreat at <strong>Marsa Wazar</strong> near <strong>Marsa Alam</strong>, Egypt. Designed for couples and solo travelers, it promises a serene <strong>Red Sea</strong> escape with a tranquil beachfront setting, elegant design, and curated experiences for those seeking peace, privacy, and coastal charm.</p>', 
          'Wazar Bay Resort', 
          'abchotels/wazar-bay-resort.webp', 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL
  ), 
  (
          'p-5', 
          'abchotels/channel-hotel.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'projects'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'project'), 
          'ABC Hotels Company provided consultancy services for Channel Hotel, supporting the business from investment planning to full operational implementation. Our role included strategic guidance on location selection, construction oversight, and setting up operations. With proven expertise in hotels, resorts, serviced apartments, and restaurants, ABC Hotels empowers business owners to bring their hospitality projects to life with confidence.', 
          'Channel hotel', 
          'abchotels/channel-hotel.webp', 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL
  ), 
  (
          'p-6', 
          'abchotels/channel-hotel.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'projects'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'project'), 
          'ABC Hotels Company provided consultancy services for Channel Hotel, supporting the business from investment planning to full operational implementation. Our role included strategic guidance on location selection, construction oversight, and setting up operations. With proven expertise in hotels, resorts, serviced apartments, and restaurants, ABC Hotels empowers business owners to bring their hospitality projects to life with confidence.', 
          'Boho Hotel', 
          'abchotels/channel-hotel.webp', 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL
  ), 
  (
          's-1', 
          'abchotels/hotels-management.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'services'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'service'), 
          '<p><strong>ABC Hotels</strong> offers full-spectrum hotel management services, designed to optimize performance and enhance guest satisfaction across all property types. Our services cover daily operations, staffing, financial oversight, brand positioning, quality assurance, and guest experience strategy. With a results-driven approach and industry expertise, we ensure each hotel operates efficiently while upholding the highest standards of hospitality.</p>', 
          'Hotels Management', 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL
  ), 
  (
          's-2', 
          'abchotels/hotel-serviced-apartments.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'services'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'service'), 
          'We offer a complete range of hotel apartment services, providing long-term guests with the ideal combination of home-like comfort with luxurious hotel amenities.', 
          'Hotel Serviced Apartments', 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL
  ), 
  (
          's-3', 
          'abchotels/property-management-system.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'services'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'service'), 
          '<p><strong>ABC Hotels</strong>’ Property Management System (PMS) is a robust, all-in-one solution that enhances property operations, integrates guest services, and provides real-time analytics to optimize revenue and streamline management tasks.</p>', 
          'Property Management', 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          'View Website', 
          NULL
  ), 
  (
          's-4', 
          'abchotels/food-and-beverage.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'services'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'service'), 
          '<p><strong>ABC Hotels </strong>delivers exceptional F&amp;B services, offering tailored culinary concepts, operational management, and strategic development for restaurants, cafés, and hotel dining outlets. Our team ensures high standards across every detail from menu creation and staff training to cost control and guest experience bringing culinary visions to life with efficiency and flair.</p>', 
          'Food and Beverage', 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL
  ), 
  (
          's-5', 
          'abchotels/yalabina-reservation-platform.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'services'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'service'), 
          '<p><strong>ABC</strong> introduces <strong>&quot;Yalabina&quot;</strong> a smart reservation platform built to enhance guest experience and boost direct bookings for property owners. With real-time availability, secure payments, and an intuitive interface, it offers guests a seamless, personalized booking journey while giving owners greater control, valuable insights, and reduced reliance on third-party platforms.</p>', 
          'Yalabina Reservation Platform', 
          NULL, 
          'https://yalabina.com', 
          NULL, 
          NULL, 
          'yalabina', 
          'https://yalabina.com'
  ), 
  (
          's-6', 
          'abchotels/consultancy.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'services'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'service'), 
          '<p><strong>ABC Hotels</strong> provides strategic consultancy for hospitality business owners, offering insights and support across investment planning, development, operations, and performance optimization. We combine market intelligence with operational expertise to turn hospitality visions into thriving assets.</p>', 
          'Consultancy', 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL, 
          NULL
  ), 
  (
          't-1', 
          'abchotels/team_Hakim-El-Nahry.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'team'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'team member'), 
          'With over four decades of experience in the hospitality industry, Hakim has progressively ascended to leadership roles since 1993. Having held senior executive positions with renowned international hospitality companies and prominent global developers, he has demonstrated exceptional expertise and leadership in driving the growth and success of the industry.', 
          'Abdel Hakim El Nahry', 
          NULL, 
          NULL, 
          NULL, 
          'CEO and Co-founder', 
          NULL, 
          NULL
  ), 
  (
          't-2', 
          'abchotels/team_Assem-Kamal.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'team'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'team member'), 
          'With a wealth of experience in the hotel and resort industry since 2004, Assem has held several senior administrative roles, including General Manager of El Alamein Hotel and Director of the Rooms Sector. He has contributed to renowned international hotels such as Radisson Blu Dubai, Nuran Green Dubai, Address Dubai Hotel, El Alamein Hotel, and Emaar Misr (Marassi). His most recent position was General Manager of El Alamein Hotel, having previously served as Director of the Rooms Sector at Emaar Misr for a period of 10 years.', 
          'Assem Kamal', 
          NULL, 
          NULL, 
          NULL, 
          'Member of the Board of Directors', 
          NULL, 
          NULL
  ), 
  (
          't-3', 
          'abchotels/team_Mohamed-Ahmed.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'team'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'team member'), 
          'With extensive experience in the hotel and resort industry since 1986, Mohamed has held several senior management positions, including Deputy General Manager and Director of the Food and Beverage sector. He has contributed to the success of renowned international hotels such as Novotel, Pyramisa, Sonesta, El Alamein Hotel, and Emaar Egypt (Marassi). His most recent position was Deputy General Manager and Food and Beverage Sector Manager at Emaar Misr.', 
          'Mohamed Ahmed', 
          NULL, 
          NULL, 
          NULL, 
          'Member of the Board of Directors', 
          NULL, 
          NULL
  ), 
  (
          't-4', 
          'abchotels/team_Mohamed-El-Koumy.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'team'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'team member'), 
          'A distinguished board member with a specialization in tourism and property management, Mohamed brings valuable expertise in these sectors, contributing significantly to the strategic direction and growth of the company.', 
          'Mohamed Elkoumy', 
          NULL, 
          NULL, 
          NULL, 
          'Member of the Board of Directors', 
          NULL, 
          NULL
  ), 
  (
          't-5', 
          'abchotels/team_Mohamed-Nafea.webp', 
          NULL, 
          NULL, 
          (SELECT section_id FROM tenants_schema.section WHERE section_name = 'team'), 
          (SELECT partial_type_id FROM tenants_schema.partial_type WHERE partial_type_name = 'team member'), 
          'A distinguished board member with a specialization in tourism and property management, Mohamed brings valuable expertise in these sectors, contributing significantly to the strategic direction and growth of the company.', 
          'Mohamed Nafea', 
          NULL, 
          NULL, 
          NULL, 
          'Member of the Board of Directors', 
          NULL, 
          NULL
  );
	
