// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: devkit/v1/accounts_role.proto

package devkitv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleCreateUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId            int32   `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName          string  `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleSecurityLevel int32   `protobuf:"varint,5,opt,name=role_security_level,json=roleSecurityLevel,proto3" json:"role_security_level,omitempty"`
	TenantId          int32   `protobuf:"varint,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RoleDescription   string  `protobuf:"bytes,3,opt,name=role_description,json=roleDescription,proto3" json:"role_description,omitempty"`
	Permissions       []int32 `protobuf:"varint,4,rep,packed,name=permissions,proto3" json:"permissions,omitempty"`
}

func (x *RoleCreateUpdateRequest) Reset() {
	*x = RoleCreateUpdateRequest{}
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleCreateUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleCreateUpdateRequest) ProtoMessage() {}

func (x *RoleCreateUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleCreateUpdateRequest.ProtoReflect.Descriptor instead.
func (*RoleCreateUpdateRequest) Descriptor() ([]byte, []int) {
	return file_devkit_v1_accounts_role_proto_rawDescGZIP(), []int{0}
}

func (x *RoleCreateUpdateRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RoleCreateUpdateRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleCreateUpdateRequest) GetRoleSecurityLevel() int32 {
	if x != nil {
		return x.RoleSecurityLevel
	}
	return 0
}

func (x *RoleCreateUpdateRequest) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *RoleCreateUpdateRequest) GetRoleDescription() string {
	if x != nil {
		return x.RoleDescription
	}
	return ""
}

func (x *RoleCreateUpdateRequest) GetPermissions() []int32 {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type AccountsSchemaRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId          int32  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName        string `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	TenantId        int32  `protobuf:"varint,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RoleDescription string `protobuf:"bytes,3,opt,name=role_description,json=roleDescription,proto3" json:"role_description,omitempty"`
	CreatedAt       string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt       string `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *AccountsSchemaRole) Reset() {
	*x = AccountsSchemaRole{}
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountsSchemaRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountsSchemaRole) ProtoMessage() {}

func (x *AccountsSchemaRole) ProtoReflect() protoreflect.Message {
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountsSchemaRole.ProtoReflect.Descriptor instead.
func (*AccountsSchemaRole) Descriptor() ([]byte, []int) {
	return file_devkit_v1_accounts_role_proto_rawDescGZIP(), []int{1}
}

func (x *AccountsSchemaRole) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *AccountsSchemaRole) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *AccountsSchemaRole) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *AccountsSchemaRole) GetRoleDescription() string {
	if x != nil {
		return x.RoleDescription
	}
	return ""
}

func (x *AccountsSchemaRole) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AccountsSchemaRole) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *AccountsSchemaRole) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type RoleCreateUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role *AccountsSchemaRole `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *RoleCreateUpdateResponse) Reset() {
	*x = RoleCreateUpdateResponse{}
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleCreateUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleCreateUpdateResponse) ProtoMessage() {}

func (x *RoleCreateUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleCreateUpdateResponse.ProtoReflect.Descriptor instead.
func (*RoleCreateUpdateResponse) Descriptor() ([]byte, []int) {
	return file_devkit_v1_accounts_role_proto_rawDescGZIP(), []int{2}
}

func (x *RoleCreateUpdateResponse) GetRole() *AccountsSchemaRole {
	if x != nil {
		return x.Role
	}
	return nil
}

type RoleDeleteRestoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []int32 `protobuf:"varint,1,rep,packed,name=records,proto3" json:"records,omitempty"`
}

func (x *RoleDeleteRestoreRequest) Reset() {
	*x = RoleDeleteRestoreRequest{}
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleDeleteRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDeleteRestoreRequest) ProtoMessage() {}

func (x *RoleDeleteRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDeleteRestoreRequest.ProtoReflect.Descriptor instead.
func (*RoleDeleteRestoreRequest) Descriptor() ([]byte, []int) {
	return file_devkit_v1_accounts_role_proto_rawDescGZIP(), []int{3}
}

func (x *RoleDeleteRestoreRequest) GetRecords() []int32 {
	if x != nil {
		return x.Records
	}
	return nil
}

type RoleDeleteRestoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*AccountsSchemaRole `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *RoleDeleteRestoreResponse) Reset() {
	*x = RoleDeleteRestoreResponse{}
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleDeleteRestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDeleteRestoreResponse) ProtoMessage() {}

func (x *RoleDeleteRestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDeleteRestoreResponse.ProtoReflect.Descriptor instead.
func (*RoleDeleteRestoreResponse) Descriptor() ([]byte, []int) {
	return file_devkit_v1_accounts_role_proto_rawDescGZIP(), []int{4}
}

func (x *RoleDeleteRestoreResponse) GetRecords() []*AccountsSchemaRole {
	if x != nil {
		return x.Records
	}
	return nil
}

type RoleDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record int32 `protobuf:"varint,1,opt,name=record,proto3" json:"record,omitempty"`
}

func (x *RoleDeleteRequest) Reset() {
	*x = RoleDeleteRequest{}
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDeleteRequest) ProtoMessage() {}

func (x *RoleDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDeleteRequest.ProtoReflect.Descriptor instead.
func (*RoleDeleteRequest) Descriptor() ([]byte, []int) {
	return file_devkit_v1_accounts_role_proto_rawDescGZIP(), []int{5}
}

func (x *RoleDeleteRequest) GetRecord() int32 {
	if x != nil {
		return x.Record
	}
	return 0
}

type RoleDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record *AccountsSchemaRole `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
}

func (x *RoleDeleteResponse) Reset() {
	*x = RoleDeleteResponse{}
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDeleteResponse) ProtoMessage() {}

func (x *RoleDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDeleteResponse.ProtoReflect.Descriptor instead.
func (*RoleDeleteResponse) Descriptor() ([]byte, []int) {
	return file_devkit_v1_accounts_role_proto_rawDescGZIP(), []int{6}
}

func (x *RoleDeleteResponse) GetRecord() *AccountsSchemaRole {
	if x != nil {
		return x.Record
	}
	return nil
}

type RoleListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleListRequest) Reset() {
	*x = RoleListRequest{}
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListRequest) ProtoMessage() {}

func (x *RoleListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListRequest.ProtoReflect.Descriptor instead.
func (*RoleListRequest) Descriptor() ([]byte, []int) {
	return file_devkit_v1_accounts_role_proto_rawDescGZIP(), []int{7}
}

type RoleListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records        []*AccountsSchemaRole `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	DeletedRecords []*AccountsSchemaRole `protobuf:"bytes,2,rep,name=deleted_records,json=deletedRecords,proto3" json:"deleted_records,omitempty"`
	Options        *AvailableOptions     `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *RoleListResponse) Reset() {
	*x = RoleListResponse{}
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListResponse) ProtoMessage() {}

func (x *RoleListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListResponse.ProtoReflect.Descriptor instead.
func (*RoleListResponse) Descriptor() ([]byte, []int) {
	return file_devkit_v1_accounts_role_proto_rawDescGZIP(), []int{8}
}

func (x *RoleListResponse) GetRecords() []*AccountsSchemaRole {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *RoleListResponse) GetDeletedRecords() []*AccountsSchemaRole {
	if x != nil {
		return x.DeletedRecords
	}
	return nil
}

func (x *RoleListResponse) GetOptions() *AvailableOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type RoleFindForUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordId int32 `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
}

func (x *RoleFindForUpdateRequest) Reset() {
	*x = RoleFindForUpdateRequest{}
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleFindForUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleFindForUpdateRequest) ProtoMessage() {}

func (x *RoleFindForUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleFindForUpdateRequest.ProtoReflect.Descriptor instead.
func (*RoleFindForUpdateRequest) Descriptor() ([]byte, []int) {
	return file_devkit_v1_accounts_role_proto_rawDescGZIP(), []int{9}
}

func (x *RoleFindForUpdateRequest) GetRecordId() int32 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

type RoleFindForUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *RoleCreateUpdateRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *RoleFindForUpdateResponse) Reset() {
	*x = RoleFindForUpdateResponse{}
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleFindForUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleFindForUpdateResponse) ProtoMessage() {}

func (x *RoleFindForUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleFindForUpdateResponse.ProtoReflect.Descriptor instead.
func (*RoleFindForUpdateResponse) Descriptor() ([]byte, []int) {
	return file_devkit_v1_accounts_role_proto_rawDescGZIP(), []int{10}
}

func (x *RoleFindForUpdateResponse) GetRequest() *RoleCreateUpdateRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type RoleListInputRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleListInputRequest) Reset() {
	*x = RoleListInputRequest{}
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListInputRequest) ProtoMessage() {}

func (x *RoleListInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListInputRequest.ProtoReflect.Descriptor instead.
func (*RoleListInputRequest) Descriptor() ([]byte, []int) {
	return file_devkit_v1_accounts_role_proto_rawDescGZIP(), []int{11}
}

type RoleListInputResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options []*SelectInputOption `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
}

func (x *RoleListInputResponse) Reset() {
	*x = RoleListInputResponse{}
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListInputResponse) ProtoMessage() {}

func (x *RoleListInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devkit_v1_accounts_role_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListInputResponse.ProtoReflect.Descriptor instead.
func (*RoleListInputResponse) Descriptor() ([]byte, []int) {
	return file_devkit_v1_accounts_role_proto_rawDescGZIP(), []int{12}
}

func (x *RoleListInputResponse) GetOptions() []*SelectInputOption {
	if x != nil {
		return x.Options
	}
	return nil
}

var File_devkit_v1_accounts_role_proto protoreflect.FileDescriptor

var file_devkit_v1_accounts_role_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x64, 0x65, 0x76, 0x6b, 0x69, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x64, 0x65, 0x76, 0x6b, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x16, 0x64, 0x65, 0x76, 0x6b,
	0x69, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1b, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x95, 0x02, 0x0a, 0x17, 0x52, 0x6f, 0x6c, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xba, 0x48, 0x07, 0x72, 0x05, 0x10, 0x02,
	0x18, 0xc8, 0x01, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x37, 0x0a,
	0x13, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x42, 0x07, 0xba, 0x48, 0x04, 0x1a,
	0x02, 0x20, 0x00, 0x52, 0x11, 0x72, 0x6f, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x79, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x10, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x08, 0xba,
	0x48, 0x05, 0x72, 0x03, 0x18, 0xc8, 0x01, 0x52, 0x0f, 0x72, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x42, 0x0b, 0xba,
	0x48, 0x08, 0x92, 0x01, 0x05, 0x10, 0xf4, 0x03, 0x18, 0x01, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xef, 0x01, 0x0a, 0x12, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x72, 0x6f, 0x6c,
	0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x4d, 0x0a, 0x18, 0x52, 0x6f, 0x6c,
	0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x64, 0x65, 0x76, 0x6b, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x6f,
	0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x34, 0x0a, 0x18, 0x52, 0x6f, 0x6c, 0x65,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x54,
	0x0a, 0x19, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x07, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x64,
	0x65, 0x76, 0x6b, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x73, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x07, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x22, 0x2b, 0x0a, 0x11, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x22, 0x4b, 0x0a, 0x12, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x64, 0x65, 0x76, 0x6b, 0x69, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x11,
	0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0xca, 0x01, 0x0a, 0x10, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x64, 0x65, 0x76, 0x6b, 0x69, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12,
	0x46, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x64, 0x65, 0x76, 0x6b, 0x69,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x0e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x35, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x64, 0x65, 0x76, 0x6b, 0x69,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x37,
	0x0a, 0x18, 0x52, 0x6f, 0x6c, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x6f, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x22, 0x59, 0x0a, 0x19, 0x52, 0x6f, 0x6c, 0x65, 0x46,
	0x69, 0x6e, 0x64, 0x46, 0x6f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64, 0x65, 0x76, 0x6b, 0x69, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4f, 0x0a, 0x15, 0x52, 0x6f,
	0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x65, 0x76, 0x6b, 0x69, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0xa6, 0x01, 0x0a, 0x0d,
	0x63, 0x6f, 0x6d, 0x2e, 0x64, 0x65, 0x76, 0x6b, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x42, 0x11, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64,
	0x61, 0x72, 0x77, 0x69, 0x73, 0x68, 0x64, 0x65, 0x76, 0x2f, 0x64, 0x65, 0x76, 0x6b, 0x69, 0x74,
	0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x64,
	0x65, 0x76, 0x6b, 0x69, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x64, 0x65, 0x76, 0x6b, 0x69, 0x74, 0x76,
	0x31, 0xa2, 0x02, 0x03, 0x44, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x44, 0x65, 0x76, 0x6b, 0x69, 0x74,
	0x2e, 0x56, 0x31, 0xca, 0x02, 0x09, 0x44, 0x65, 0x76, 0x6b, 0x69, 0x74, 0x5c, 0x56, 0x31, 0xe2,
	0x02, 0x15, 0x44, 0x65, 0x76, 0x6b, 0x69, 0x74, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x44, 0x65, 0x76, 0x6b, 0x69, 0x74,
	0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_devkit_v1_accounts_role_proto_rawDescOnce sync.Once
	file_devkit_v1_accounts_role_proto_rawDescData = file_devkit_v1_accounts_role_proto_rawDesc
)

func file_devkit_v1_accounts_role_proto_rawDescGZIP() []byte {
	file_devkit_v1_accounts_role_proto_rawDescOnce.Do(func() {
		file_devkit_v1_accounts_role_proto_rawDescData = protoimpl.X.CompressGZIP(file_devkit_v1_accounts_role_proto_rawDescData)
	})
	return file_devkit_v1_accounts_role_proto_rawDescData
}

var file_devkit_v1_accounts_role_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_devkit_v1_accounts_role_proto_goTypes = []any{
	(*RoleCreateUpdateRequest)(nil),   // 0: devkit.v1.RoleCreateUpdateRequest
	(*AccountsSchemaRole)(nil),        // 1: devkit.v1.AccountsSchemaRole
	(*RoleCreateUpdateResponse)(nil),  // 2: devkit.v1.RoleCreateUpdateResponse
	(*RoleDeleteRestoreRequest)(nil),  // 3: devkit.v1.RoleDeleteRestoreRequest
	(*RoleDeleteRestoreResponse)(nil), // 4: devkit.v1.RoleDeleteRestoreResponse
	(*RoleDeleteRequest)(nil),         // 5: devkit.v1.RoleDeleteRequest
	(*RoleDeleteResponse)(nil),        // 6: devkit.v1.RoleDeleteResponse
	(*RoleListRequest)(nil),           // 7: devkit.v1.RoleListRequest
	(*RoleListResponse)(nil),          // 8: devkit.v1.RoleListResponse
	(*RoleFindForUpdateRequest)(nil),  // 9: devkit.v1.RoleFindForUpdateRequest
	(*RoleFindForUpdateResponse)(nil), // 10: devkit.v1.RoleFindForUpdateResponse
	(*RoleListInputRequest)(nil),      // 11: devkit.v1.RoleListInputRequest
	(*RoleListInputResponse)(nil),     // 12: devkit.v1.RoleListInputResponse
	(*AvailableOptions)(nil),          // 13: devkit.v1.AvailableOptions
	(*SelectInputOption)(nil),         // 14: devkit.v1.SelectInputOption
}
var file_devkit_v1_accounts_role_proto_depIdxs = []int32{
	1,  // 0: devkit.v1.RoleCreateUpdateResponse.role:type_name -> devkit.v1.AccountsSchemaRole
	1,  // 1: devkit.v1.RoleDeleteRestoreResponse.records:type_name -> devkit.v1.AccountsSchemaRole
	1,  // 2: devkit.v1.RoleDeleteResponse.record:type_name -> devkit.v1.AccountsSchemaRole
	1,  // 3: devkit.v1.RoleListResponse.records:type_name -> devkit.v1.AccountsSchemaRole
	1,  // 4: devkit.v1.RoleListResponse.deleted_records:type_name -> devkit.v1.AccountsSchemaRole
	13, // 5: devkit.v1.RoleListResponse.options:type_name -> devkit.v1.AvailableOptions
	0,  // 6: devkit.v1.RoleFindForUpdateResponse.request:type_name -> devkit.v1.RoleCreateUpdateRequest
	14, // 7: devkit.v1.RoleListInputResponse.options:type_name -> devkit.v1.SelectInputOption
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_devkit_v1_accounts_role_proto_init() }
func file_devkit_v1_accounts_role_proto_init() {
	if File_devkit_v1_accounts_role_proto != nil {
		return
	}
	file_devkit_v1_client_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_devkit_v1_accounts_role_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_devkit_v1_accounts_role_proto_goTypes,
		DependencyIndexes: file_devkit_v1_accounts_role_proto_depIdxs,
		MessageInfos:      file_devkit_v1_accounts_role_proto_msgTypes,
	}.Build()
	File_devkit_v1_accounts_role_proto = out.File
	file_devkit_v1_accounts_role_proto_rawDesc = nil
	file_devkit_v1_accounts_role_proto_goTypes = nil
	file_devkit_v1_accounts_role_proto_depIdxs = nil
}
