// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountsSchemaPermission struct {
	PermissionID          int32       `json:"permission_id"`
	PermissionFunction    string      `json:"permission_function"`
	PermissionName        string      `json:"permission_name"`
	PermissionDescription pgtype.Text `json:"permission_description"`
	PermissionGroup       string      `json:"permission_group"`
}

type AccountsSchemaRole struct {
	RoleID          int32            `json:"role_id"`
	RoleName        string           `json:"role_name"`
	RoleDescription pgtype.Text      `json:"role_description"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	DeletedAt       pgtype.Timestamp `json:"deleted_at"`
}

type AccountsSchemaRolePermission struct {
	RoleID       int32 `json:"role_id"`
	PermissionID int32 `json:"permission_id"`
}
