// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountsSchemaNavigationBar struct {
	NavigationBarID   int32  `json:"navigation_bar_id"`
	NavigationBarName string `json:"navigation_bar_name"`
}

type AccountsSchemaNavigationBarItem struct {
	NavigationBarItemID int32       `json:"navigation_bar_item_id"`
	MenuKey             string      `json:"menu_key"`
	Label               string      `json:"label"`
	LabelAr             pgtype.Text `json:"label_ar"`
	Icon                pgtype.Text `json:"icon"`
	NavigationBarID     pgtype.Int4 `json:"navigation_bar_id"`
	ParentID            pgtype.Int4 `json:"parent_id"`
	PermissionID        pgtype.Int4 `json:"permission_id"`
	Route               pgtype.Text `json:"route"`
}

type AccountsSchemaPermission struct {
	PermissionID          int32       `json:"permission_id"`
	PermissionFunction    string      `json:"permission_function"`
	PermissionName        string      `json:"permission_name"`
	PermissionDescription pgtype.Text `json:"permission_description"`
	PermissionGroup       string      `json:"permission_group"`
}

type AccountsSchemaRole struct {
	RoleID            int32            `json:"role_id"`
	TenantID          pgtype.Int4      `json:"tenant_id"`
	RoleName          string           `json:"role_name"`
	RoleSecurityLevel int32            `json:"role_security_level"`
	RoleDescription   pgtype.Text      `json:"role_description"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	DeletedAt         pgtype.Timestamp `json:"deleted_at"`
}

type AccountsSchemaRolePermission struct {
	RoleID       int32 `json:"role_id"`
	PermissionID int32 `json:"permission_id"`
}

type AccountsSchemaUser struct {
	UserID       int32            `json:"user_id"`
	UserName     string           `json:"user_name"`
	TenantID     pgtype.Int4      `json:"tenant_id"`
	UserTypeID   int32            `json:"user_type_id"`
	UserPhone    pgtype.Text      `json:"user_phone"`
	UserEmail    string           `json:"user_email"`
	UserPassword pgtype.Text      `json:"user_password"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
}

type AccountsSchemaUserRole struct {
	UserID int32 `json:"user_id"`
	RoleID int32 `json:"role_id"`
}

type AccountsSchemaUserType struct {
	UserTypeID   int32  `json:"user_type_id"`
	UserTypeName string `json:"user_type_name"`
}

type Icon struct {
	IconID      int32  `json:"icon_id"`
	IconName    string `json:"icon_name"`
	IconContent string `json:"icon_content"`
}

type InputType struct {
	InputTypeID   int32  `json:"input_type_id"`
	InputTypeName string `json:"input_type_name"`
}

type Log struct {
	LogID          int32            `json:"log_id"`
	LogTitle       string           `json:"log_title"`
	UserID         int32            `json:"user_id"`
	RecordID       pgtype.Int4      `json:"record_id"`
	ActionName     pgtype.Text      `json:"action_name"`
	TableName      pgtype.Text      `json:"table_name"`
	PermissionName pgtype.Text      `json:"permission_name"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type PropertiesSchemaAmenity struct {
	AmenityID           int32            `json:"amenity_id"`
	AmenityGroupID      int32            `json:"amenity_group_id"`
	AmenityName         string           `json:"amenity_name"`
	AmenityNameAr       pgtype.Text      `json:"amenity_name_ar"`
	AmenityIcon         pgtype.Text      `json:"amenity_icon"`
	AmenityInputLabel   pgtype.Text      `json:"amenity_input_label"`
	AmenityInputLabelAr pgtype.Text      `json:"amenity_input_label_ar"`
	AmenityValueTypeID  int32            `json:"amenity_value_type_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	DeletedAt           pgtype.Timestamp `json:"deleted_at"`
}

type PropertiesSchemaAmenityGroup struct {
	AmenityGroupID     int32            `json:"amenity_group_id"`
	AmenityGroupName   string           `json:"amenity_group_name"`
	PropertyCategoryID pgtype.Int4      `json:"property_category_id"`
	AmenityGroupIcon   pgtype.Text      `json:"amenity_group_icon"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	DeletedAt          pgtype.Timestamp `json:"deleted_at"`
}

type PropertiesSchemaAmenityValueType struct {
	AmenityValueTypeID int32  `json:"amenity_value_type_id"`
	AmenityValueType   string `json:"amenity_value_type"`
}

type PropertiesSchemaBedType struct {
	BedTypeID   int32         `json:"bed_type_id"`
	BedType     string        `json:"bed_type"`
	BedTypeAr   pgtype.Text   `json:"bed_type_ar"`
	BedLength   pgtype.Float4 `json:"bed_length"`
	BedWidth    pgtype.Float4 `json:"bed_width"`
	BedTypeIcon pgtype.Text   `json:"bed_type_icon"`
}

type PropertiesSchemaCity struct {
	CityID     int32            `json:"city_id"`
	CityName   string           `json:"city_name"`
	CityNameAr pgtype.Text      `json:"city_name_ar"`
	CityImage  pgtype.Text      `json:"city_image"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}

type PropertiesSchemaCompound struct {
	CompoundID     int32            `json:"compound_id"`
	CompoundName   string           `json:"compound_name"`
	CompoundNameAr pgtype.Text      `json:"compound_name_ar"`
	CompoundImage  pgtype.Text      `json:"compound_image"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
}

type PropertiesSchemaLocation struct {
	LocationID     int32            `json:"location_id"`
	CityID         int32            `json:"city_id"`
	LocationName   string           `json:"location_name"`
	LocationNameAr pgtype.Text      `json:"location_name_ar"`
	LocationImage  pgtype.Text      `json:"location_image"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
}

type PropertiesSchemaProperty struct {
	PropertyID            int32            `json:"property_id"`
	PropertyName          string           `json:"property_name"`
	PropertyNameAr        pgtype.Text      `json:"property_name_ar"`
	AddressLine           string           `json:"address_line"`
	AddressLineAr         pgtype.Text      `json:"address_line_ar"`
	InstantApprove        pgtype.Bool      `json:"instant_approve"`
	StarRating            pgtype.Int4      `json:"star_rating"`
	IframeUrl             pgtype.Text      `json:"iframe_url"`
	LocationUrl           string           `json:"location_url"`
	PropertyTypeID        int32            `json:"property_type_id"`
	LocationID            int32            `json:"location_id"`
	CompoundID            pgtype.Int4      `json:"compound_id"`
	TenantID              int32            `json:"tenant_id"`
	PropertyImage         pgtype.Text      `json:"property_image"`
	PropertyImages        pgtype.Text      `json:"property_images"`
	PropertyDescription   pgtype.Text      `json:"property_description"`
	PropertyDescriptionAr pgtype.Text      `json:"property_description_ar"`
	CheckinTimeFrom       pgtype.Time      `json:"checkin_time_from"`
	CheckinTimeTo         pgtype.Time      `json:"checkin_time_to"`
	CheckoutTimeFrom      pgtype.Time      `json:"checkout_time_from"`
	CheckoutTimeTo        pgtype.Time      `json:"checkout_time_to"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
	DeletedAt             pgtype.Timestamp `json:"deleted_at"`
}

type PropertiesSchemaPropertyCategory struct {
	PropertyCategoryID   int32            `json:"property_category_id"`
	PropertyCategoryName string           `json:"property_category_name"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	DeletedAt            pgtype.Timestamp `json:"deleted_at"`
}

type PropertiesSchemaPropertyType struct {
	PropertyTypeID     int32            `json:"property_type_id"`
	PropertyTypeName   string           `json:"property_type_name"`
	PropertyTypeNameAr pgtype.Text      `json:"property_type_name_ar"`
	PropertyTypeIcon   pgtype.Text      `json:"property_type_icon"`
	PropertyCategoryID int32            `json:"property_category_id"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	DeletedAt          pgtype.Timestamp `json:"deleted_at"`
}

type PropertiesSchemaReservableUnit struct {
	ReservableUnitID            int32            `json:"reservable_unit_id"`
	ReservableUnitName          string           `json:"reservable_unit_name"`
	ReservableUnitNameAr        pgtype.Text      `json:"reservable_unit_name_ar"`
	ReservableUnitDescription   pgtype.Text      `json:"reservable_unit_description"`
	ReservableUnitDescriptionAr pgtype.Text      `json:"reservable_unit_description_ar"`
	MinimumGuestsNumber         int32            `json:"minimum_guests_number"`
	MaximumGuestsNumber         int32            `json:"maximum_guests_number"`
	UnitArea                    float32          `json:"unit_area"`
	ReservableUnitTypeID        int32            `json:"reservable_unit_type_id"`
	PropertyID                  int32            `json:"property_id"`
	BathroomsCount              int32            `json:"bathrooms_count"`
	IsClosed                    pgtype.Bool      `json:"is_closed"`
	BasePrice                   pgtype.Float4    `json:"base_price"`
	ReservableUnitImage         pgtype.Text      `json:"reservable_unit_image"`
	ReservableUnitImages        pgtype.Text      `json:"reservable_unit_images"`
	CreatedAt                   pgtype.Timestamp `json:"created_at"`
	UpdatedAt                   pgtype.Timestamp `json:"updated_at"`
	DeletedAt                   pgtype.Timestamp `json:"deleted_at"`
}

type PropertiesSchemaReservableUnitRoom struct {
	ReservableUnitRoomID     int32            `json:"reservable_unit_room_id"`
	ReservableUnitRoomName   string           `json:"reservable_unit_room_name"`
	ReservableUnitRoomImage  pgtype.Text      `json:"reservable_unit_room_image"`
	ReservableUnitRoomImages pgtype.Text      `json:"reservable_unit_room_images"`
	ReservableUnitID         int32            `json:"reservable_unit_id"`
	CreatedAt                pgtype.Timestamp `json:"created_at"`
	UpdatedAt                pgtype.Timestamp `json:"updated_at"`
	DeletedAt                pgtype.Timestamp `json:"deleted_at"`
}

type PropertiesSchemaReservableUnitRoomBed struct {
	ReservableUnitRoomID int32 `json:"reservable_unit_room_id"`
	BedTypeID            int32 `json:"bed_type_id"`
	BedCount             int32 `json:"bed_count"`
}

type PropertiesSchemaReservableUnitType struct {
	ReservableUnitTypeID     int32       `json:"reservable_unit_type_id"`
	ReservableUnitTypeName   string      `json:"reservable_unit_type_name"`
	ReservableUnitTypeNameAr pgtype.Text `json:"reservable_unit_type_name_ar"`
	PropertyCategoryID       int32       `json:"property_category_id"`
	RoomsCount               int32       `json:"rooms_count"`
}

type PropertiesSchemaUnitAmenity struct {
	UnitID       int32       `json:"unit_id"`
	UnitType     string      `json:"unit_type"`
	IsFeatured   pgtype.Bool `json:"is_featured"`
	AmenityID    int32       `json:"amenity_id"`
	AmenityValue pgtype.Text `json:"amenity_value"`
}

type Setting struct {
	SettingID    int32            `json:"setting_id"`
	InputTypeID  int32            `json:"input_type_id"`
	SettingKey   string           `json:"setting_key"`
	SettingValue string           `json:"setting_value"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Tag struct {
	Tag string `json:"tag"`
}

type TenantsSchemaPage struct {
	PageID              int32            `json:"page_id"`
	PageName            string           `json:"page_name"`
	PageNameAr          pgtype.Text      `json:"page_name_ar"`
	PageDescription     pgtype.Text      `json:"page_description"`
	PageDescriptionAr   pgtype.Text      `json:"page_description_ar"`
	PageBreadcrumb      pgtype.Text      `json:"page_breadcrumb"`
	TenantID            pgtype.Int4      `json:"tenant_id"`
	PageRoute           string           `json:"page_route"`
	PageCoverImage      pgtype.Text      `json:"page_cover_image"`
	PageCoverVideo      pgtype.Text      `json:"page_cover_video"`
	PageKeyWords        pgtype.Text      `json:"page_key_words"`
	PageMetaDescription pgtype.Text      `json:"page_meta_description"`
	PageIcon            pgtype.Text      `json:"page_icon"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	DeletedAt           pgtype.Timestamp `json:"deleted_at"`
}

type TenantsSchemaPageSection struct {
	PageID        int32       `json:"page_id"`
	SectionID     int32       `json:"section_id"`
	PartialTypeID int32       `json:"partial_type_id"`
	IsFeatured    pgtype.Bool `json:"is_featured"`
}

type TenantsSchemaPartial struct {
	PartialID      int32            `json:"partial_id"`
	PartialName    string           `json:"partial_name"`
	PartialTypeID  int32            `json:"partial_type_id"`
	TenantID       pgtype.Int4      `json:"tenant_id"`
	PartialImage   pgtype.Text      `json:"partial_image"`
	PartialImages  pgtype.Text      `json:"partial_images"`
	PartialVideo   pgtype.Text      `json:"partial_video"`
	IsFeatured     pgtype.Bool      `json:"is_featured"`
	PartialBrief   pgtype.Text      `json:"partial_brief"`
	PartialContent pgtype.Text      `json:"partial_content"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
}

type TenantsSchemaPartialType struct {
	PartialTypeID   int32  `json:"partial_type_id"`
	PartialTypeName string `json:"partial_type_name"`
}

type TenantsSchemaSection struct {
	SectionID            int32            `json:"section_id"`
	SectionName          string           `json:"section_name"`
	SectionNameAr        pgtype.Text      `json:"section_name_ar"`
	SectionDescription   pgtype.Text      `json:"section_description"`
	SectionDescriptionAr pgtype.Text      `json:"section_description_ar"`
	TenantID             pgtype.Int4      `json:"tenant_id"`
	SectionBackground    pgtype.Text      `json:"section_background"`
	SectionImages        pgtype.Text      `json:"section_images"`
	SectionIcon          pgtype.Text      `json:"section_icon"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	DeletedAt            pgtype.Timestamp `json:"deleted_at"`
}

type TenantsSchemaTenant struct {
	TenantID               int32            `json:"tenant_id"`
	TenantName             string           `json:"tenant_name"`
	TenantNameAr           pgtype.Text      `json:"tenant_name_ar"`
	TenantPhone            pgtype.Text      `json:"tenant_phone"`
	TenantAddress          pgtype.Text      `json:"tenant_address"`
	TenantAddressAr        pgtype.Text      `json:"tenant_address_ar"`
	TenantDescription      pgtype.Text      `json:"tenant_description"`
	TenantDescriptionAr    pgtype.Text      `json:"tenant_description_ar"`
	TenantEmail            pgtype.Text      `json:"tenant_email"`
	TenantLogo             pgtype.Text      `json:"tenant_logo"`
	TenantLogoVertical     pgtype.Text      `json:"tenant_logo_vertical"`
	TenantLogoDark         pgtype.Text      `json:"tenant_logo_dark"`
	TenantLogoDarkVertical pgtype.Text      `json:"tenant_logo_dark_vertical"`
	TenantValues           pgtype.Text      `json:"tenant_values"`
	TenantMission          pgtype.Text      `json:"tenant_mission"`
	TenantVision           pgtype.Text      `json:"tenant_vision"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	DeletedAt              pgtype.Timestamp `json:"deleted_at"`
}

type Translation struct {
	TranslationKey string `json:"translation_key"`
	ArabicValue    string `json:"arabic_value"`
	EnglishValue   string `json:"english_value"`
}
