// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CityList(ctx context.Context) ([]PropertiesSchemaCity, error)
	CityListInput(ctx context.Context) ([]CityListInputRow, error)
	IconCreateUpdateBulk(ctx context.Context, arg IconCreateUpdateBulkParams) ([]Icon, error)
	IconFind(ctx context.Context, arg IconFindParams) (Icon, error)
	IconList(ctx context.Context) ([]Icon, error)
	LocationList(ctx context.Context) ([]PropertiesSchemaLocation, error)
	LocationListInput(ctx context.Context, arg LocationListInputParams) ([]LocationListInputRow, error)
	PageCreateUpdate(ctx context.Context, arg PageCreateUpdateParams) (TenantsSchemaPage, error)
	PageDeleteRestore(ctx context.Context, records []int32) ([]TenantsSchemaPage, error)
	PageList(ctx context.Context, tenantID int32) ([]TenantsSchemaPage, error)
	PartialCreateUpdate(ctx context.Context, arg PartialCreateUpdateParams) (TenantsSchemaPartial, error)
	PartialDeleteRestore(ctx context.Context, records []int32) ([]TenantsSchemaPartial, error)
	PartialList(ctx context.Context, tenantID int32) ([]TenantsSchemaPartial, error)
	RoleCreateUpdate(ctx context.Context, arg RoleCreateUpdateParams) (AccountsSchemaRole, error)
	RoleDelete(ctx context.Context, arg RoleDeleteParams) (AccountsSchemaRole, error)
	RoleDeleteRestore(ctx context.Context, arg RoleDeleteRestoreParams) (AccountsSchemaRole, error)
	RoleFindForUpdate(ctx context.Context, roleID int32) (RoleFindForUpdateRow, error)
	RoleList(ctx context.Context, arg RoleListParams) ([]RoleListRow, error)
	RoleListInput(ctx context.Context, callerID int32) ([]RoleListInputRow, error)
	SectionCreateUpdate(ctx context.Context, arg SectionCreateUpdateParams) (TenantsSchemaSection, error)
	SectionDeleteRestore(ctx context.Context, records []int32) ([]TenantsSchemaSection, error)
	SectionList(ctx context.Context, tenantID int32) ([]TenantsSchemaSection, error)
	SettingFindForUpdate(ctx context.Context) ([]SettingFindForUpdateRow, error)
	SettingUpdate(ctx context.Context, arg SettingUpdateParams) (SettingUpdateRow, error)
	TenantCreateUpdate(ctx context.Context, arg TenantCreateUpdateParams) (TenantsSchemaTenant, error)
	TenantDeleteRestore(ctx context.Context, records []int32) ([]TenantsSchemaTenant, error)
	TenantList(ctx context.Context, tenantID int32) ([]TenantsSchemaTenant, error)
	TranslationCreateUpdateBulk(ctx context.Context, arg TranslationCreateUpdateBulkParams) ([]TranslationCreateUpdateBulkRow, error)
	TranslationDelete(ctx context.Context, keys []string) ([]Translation, error)
	TranslationList(ctx context.Context) ([]Translation, error)
	UserCreateUpdate(ctx context.Context, arg UserCreateUpdateParams) (AccountsSchemaUser, error)
	UserDelete(ctx context.Context, arg UserDeleteParams) (AccountsSchemaUser, error)
	UserDeleteRestore(ctx context.Context, arg UserDeleteRestoreParams) (AccountsSchemaUser, error)
	UserFind(ctx context.Context, arg UserFindParams) (AccountsSchemaUser, error)
	UserFindForUpdate(ctx context.Context, userID int32) (UserFindForUpdateRow, error)
	UserList(ctx context.Context) ([]AccountsSchemaUser, error)
	UserListInput(ctx context.Context, callerID int32) ([]UserListInputRow, error)
	UserNavigationBarFind(ctx context.Context, arg UserNavigationBarFindParams) ([]UserNavigationBarFindRow, error)
	UserPermissionsMap(ctx context.Context, userID int32) ([]UserPermissionsMapRow, error)
	UserResetPassword(ctx context.Context, arg UserResetPasswordParams) error
}

var _ Querier = (*Queries)(nil)
