// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/darwishdev/devkit-api/db (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	connect "connectrpc.com/connect"
	db "github.com/darwishdev/devkit-api/db"
	gomock "github.com/golang/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AuthUserIDFindByEmail mocks base method.
func (m *MockStore) AuthUserIDFindByEmail(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthUserIDFindByEmail", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthUserIDFindByEmail indicates an expected call of AuthUserIDFindByEmail.
func (mr *MockStoreMockRecorder) AuthUserIDFindByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthUserIDFindByEmail", reflect.TypeOf((*MockStore)(nil).AuthUserIDFindByEmail), arg0, arg1)
}

// DbErrorParser mocks base method.
func (m *MockStore) DbErrorParser(arg0 error, arg1 map[string]string) *connect.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DbErrorParser", arg0, arg1)
	ret0, _ := ret[0].(*connect.Error)
	return ret0
}

// DbErrorParser indicates an expected call of DbErrorParser.
func (mr *MockStoreMockRecorder) DbErrorParser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DbErrorParser", reflect.TypeOf((*MockStore)(nil).DbErrorParser), arg0, arg1)
}

// ExecTX mocks base method.
func (m *MockStore) ExecTX(arg0 context.Context, arg1 func(*db.Queries) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecTX", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecTX indicates an expected call of ExecTX.
func (mr *MockStoreMockRecorder) ExecTX(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecTX", reflect.TypeOf((*MockStore)(nil).ExecTX), arg0, arg1)
}

// IconCreateUpdateBulk mocks base method.
func (m *MockStore) IconCreateUpdateBulk(arg0 context.Context, arg1 db.IconCreateUpdateBulkParams) ([]db.Icon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IconCreateUpdateBulk", arg0, arg1)
	ret0, _ := ret[0].([]db.Icon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IconCreateUpdateBulk indicates an expected call of IconCreateUpdateBulk.
func (mr *MockStoreMockRecorder) IconCreateUpdateBulk(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IconCreateUpdateBulk", reflect.TypeOf((*MockStore)(nil).IconCreateUpdateBulk), arg0, arg1)
}

// IconList mocks base method.
func (m *MockStore) IconList(arg0 context.Context) ([]db.Icon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IconList", arg0)
	ret0, _ := ret[0].([]db.Icon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IconList indicates an expected call of IconList.
func (mr *MockStoreMockRecorder) IconList(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IconList", reflect.TypeOf((*MockStore)(nil).IconList), arg0)
}

// RoleCreateUpdate mocks base method.
func (m *MockStore) RoleCreateUpdate(arg0 context.Context, arg1 db.RoleCreateUpdateParams) (db.AccountsSchemaRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleCreateUpdate", arg0, arg1)
	ret0, _ := ret[0].(db.AccountsSchemaRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoleCreateUpdate indicates an expected call of RoleCreateUpdate.
func (mr *MockStoreMockRecorder) RoleCreateUpdate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleCreateUpdate", reflect.TypeOf((*MockStore)(nil).RoleCreateUpdate), arg0, arg1)
}

// RoleDeleteRestore mocks base method.
func (m *MockStore) RoleDeleteRestore(arg0 context.Context, arg1 []int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleDeleteRestore", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RoleDeleteRestore indicates an expected call of RoleDeleteRestore.
func (mr *MockStoreMockRecorder) RoleDeleteRestore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleDeleteRestore", reflect.TypeOf((*MockStore)(nil).RoleDeleteRestore), arg0, arg1)
}

// RoleList mocks base method.
func (m *MockStore) RoleList(arg0 context.Context) ([]db.AccountsSchemaRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleList", arg0)
	ret0, _ := ret[0].([]db.AccountsSchemaRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoleList indicates an expected call of RoleList.
func (mr *MockStoreMockRecorder) RoleList(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleList", reflect.TypeOf((*MockStore)(nil).RoleList), arg0)
}

// RoleListInput mocks base method.
func (m *MockStore) RoleListInput(arg0 context.Context, arg1 int32) ([]db.RoleListInputRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleListInput", arg0, arg1)
	ret0, _ := ret[0].([]db.RoleListInputRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoleListInput indicates an expected call of RoleListInput.
func (mr *MockStoreMockRecorder) RoleListInput(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleListInput", reflect.TypeOf((*MockStore)(nil).RoleListInput), arg0, arg1)
}

// SettingFindForUpdate mocks base method.
func (m *MockStore) SettingFindForUpdate(arg0 context.Context) ([]db.SettingFindForUpdateRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SettingFindForUpdate", arg0)
	ret0, _ := ret[0].([]db.SettingFindForUpdateRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SettingFindForUpdate indicates an expected call of SettingFindForUpdate.
func (mr *MockStoreMockRecorder) SettingFindForUpdate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SettingFindForUpdate", reflect.TypeOf((*MockStore)(nil).SettingFindForUpdate), arg0)
}

// SettingUpdate mocks base method.
func (m *MockStore) SettingUpdate(arg0 context.Context, arg1 db.SettingUpdateParams) (db.SettingUpdateRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SettingUpdate", arg0, arg1)
	ret0, _ := ret[0].(db.SettingUpdateRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SettingUpdate indicates an expected call of SettingUpdate.
func (mr *MockStoreMockRecorder) SettingUpdate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SettingUpdate", reflect.TypeOf((*MockStore)(nil).SettingUpdate), arg0, arg1)
}

// TranslationCreateUpdateBulk mocks base method.
func (m *MockStore) TranslationCreateUpdateBulk(arg0 context.Context, arg1 db.TranslationCreateUpdateBulkParams) ([]db.TranslationCreateUpdateBulkRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranslationCreateUpdateBulk", arg0, arg1)
	ret0, _ := ret[0].([]db.TranslationCreateUpdateBulkRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TranslationCreateUpdateBulk indicates an expected call of TranslationCreateUpdateBulk.
func (mr *MockStoreMockRecorder) TranslationCreateUpdateBulk(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranslationCreateUpdateBulk", reflect.TypeOf((*MockStore)(nil).TranslationCreateUpdateBulk), arg0, arg1)
}

// TranslationDelete mocks base method.
func (m *MockStore) TranslationDelete(arg0 context.Context, arg1 []string) ([]db.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranslationDelete", arg0, arg1)
	ret0, _ := ret[0].([]db.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TranslationDelete indicates an expected call of TranslationDelete.
func (mr *MockStoreMockRecorder) TranslationDelete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranslationDelete", reflect.TypeOf((*MockStore)(nil).TranslationDelete), arg0, arg1)
}

// TranslationList mocks base method.
func (m *MockStore) TranslationList(arg0 context.Context) ([]db.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranslationList", arg0)
	ret0, _ := ret[0].([]db.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TranslationList indicates an expected call of TranslationList.
func (mr *MockStoreMockRecorder) TranslationList(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranslationList", reflect.TypeOf((*MockStore)(nil).TranslationList), arg0)
}

// UserCreateUpdate mocks base method.
func (m *MockStore) UserCreateUpdate(arg0 context.Context, arg1 db.UserCreateUpdateParams) (db.AccountsSchemaUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserCreateUpdate", arg0, arg1)
	ret0, _ := ret[0].(db.AccountsSchemaUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserCreateUpdate indicates an expected call of UserCreateUpdate.
func (mr *MockStoreMockRecorder) UserCreateUpdate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserCreateUpdate", reflect.TypeOf((*MockStore)(nil).UserCreateUpdate), arg0, arg1)
}

// UserDelete mocks base method.
func (m *MockStore) UserDelete(arg0 context.Context, arg1 db.UserDeleteParams) (db.AccountsSchemaUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserDelete", arg0, arg1)
	ret0, _ := ret[0].(db.AccountsSchemaUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserDelete indicates an expected call of UserDelete.
func (mr *MockStoreMockRecorder) UserDelete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserDelete", reflect.TypeOf((*MockStore)(nil).UserDelete), arg0, arg1)
}

// UserDeleteRestore mocks base method.
func (m *MockStore) UserDeleteRestore(arg0 context.Context, arg1 db.UserDeleteRestoreParams) (db.AccountsSchemaUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserDeleteRestore", arg0, arg1)
	ret0, _ := ret[0].(db.AccountsSchemaUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserDeleteRestore indicates an expected call of UserDeleteRestore.
func (mr *MockStoreMockRecorder) UserDeleteRestore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserDeleteRestore", reflect.TypeOf((*MockStore)(nil).UserDeleteRestore), arg0, arg1)
}

// UserFind mocks base method.
func (m *MockStore) UserFind(arg0 context.Context, arg1 db.UserFindParams) (db.AccountsSchemaUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserFind", arg0, arg1)
	ret0, _ := ret[0].(db.AccountsSchemaUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserFind indicates an expected call of UserFind.
func (mr *MockStoreMockRecorder) UserFind(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserFind", reflect.TypeOf((*MockStore)(nil).UserFind), arg0, arg1)
}

// UserFindForUpdate mocks base method.
func (m *MockStore) UserFindForUpdate(arg0 context.Context, arg1 int32) (db.UserFindForUpdateRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserFindForUpdate", arg0, arg1)
	ret0, _ := ret[0].(db.UserFindForUpdateRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserFindForUpdate indicates an expected call of UserFindForUpdate.
func (mr *MockStoreMockRecorder) UserFindForUpdate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserFindForUpdate", reflect.TypeOf((*MockStore)(nil).UserFindForUpdate), arg0, arg1)
}

// UserList mocks base method.
func (m *MockStore) UserList(arg0 context.Context) ([]db.AccountsSchemaUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserList", arg0)
	ret0, _ := ret[0].([]db.AccountsSchemaUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserList indicates an expected call of UserList.
func (mr *MockStoreMockRecorder) UserList(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserList", reflect.TypeOf((*MockStore)(nil).UserList), arg0)
}

// UserListInput mocks base method.
func (m *MockStore) UserListInput(arg0 context.Context, arg1 int32) ([]db.UserListInputRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserListInput", arg0, arg1)
	ret0, _ := ret[0].([]db.UserListInputRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserListInput indicates an expected call of UserListInput.
func (mr *MockStoreMockRecorder) UserListInput(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserListInput", reflect.TypeOf((*MockStore)(nil).UserListInput), arg0, arg1)
}

// UserNavigationBarFind mocks base method.
func (m *MockStore) UserNavigationBarFind(arg0 context.Context, arg1 db.UserNavigationBarFindParams) ([]db.UserNavigationBarFindRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserNavigationBarFind", arg0, arg1)
	ret0, _ := ret[0].([]db.UserNavigationBarFindRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserNavigationBarFind indicates an expected call of UserNavigationBarFind.
func (mr *MockStoreMockRecorder) UserNavigationBarFind(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserNavigationBarFind", reflect.TypeOf((*MockStore)(nil).UserNavigationBarFind), arg0, arg1)
}

// UserPermissionsMap mocks base method.
func (m *MockStore) UserPermissionsMap(arg0 context.Context, arg1 int32) ([]db.UserPermissionsMapRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserPermissionsMap", arg0, arg1)
	ret0, _ := ret[0].([]db.UserPermissionsMapRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserPermissionsMap indicates an expected call of UserPermissionsMap.
func (mr *MockStoreMockRecorder) UserPermissionsMap(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserPermissionsMap", reflect.TypeOf((*MockStore)(nil).UserPermissionsMap), arg0, arg1)
}

// UserResetPassword mocks base method.
func (m *MockStore) UserResetPassword(arg0 context.Context, arg1 db.UserResetPasswordParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserResetPassword", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UserResetPassword indicates an expected call of UserResetPassword.
func (mr *MockStoreMockRecorder) UserResetPassword(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserResetPassword", reflect.TypeOf((*MockStore)(nil).UserResetPassword), arg0, arg1)
}
